import HeaderAdmin from "@/components/admin/header.admin";
import NavbarAdmin from "@/components/admin/navbar.admin";

export const metadata = {
  title: "Admin",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="grid-cols-6 grid">
      <div className=" col-span-1 bg-[#263e4e] min-h-screen">
        <NavbarAdmin />
      </div>
      <div className="col-span-5 bg-[#edf1f6] flex flex-col overflow-auto">
        <HeaderAdmin />
        <div className="h-full p-4">{children}</div>
      </div>
    </div>
  );
}
